export const LOAD_BUSS_STATIONS = 'LOAD_BUSS_STATIONS';
export const CLEAR_BUSS_STATIONS = 'CLEAR_BUSS_STATIONS';
export const LOAD_BUSS_STATION = 'LOAD_BUSS_STATION';

export const RECEIVE_NEW_BUSS_LOCATION_ALL = 'RECEIVE_NEW_BUSS_LOCATION_ALL';
export const RECEIVE_NEW_BUSS_LOCATION_ONE = 'RECEIVE_NEW_BUSS_LOCATION_ONE';
export const SEND_NEW_BUSS_LOCATION = 'SEND_NEW_BUSS_LOCATION';

export const LOAD_LINE_NUMBERS = 'LOAD_LINE_NUMBERS';

export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET_MESSAGE';
export const WEBSOCKET_SEND = 'WEBSOCKET_SEND';
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET_DISCONNECT';