export const LOAD_BUSS_STATION = 'LOAD_BUSS_STATION';

export const RECEIVE_NEW_BUSS_LOCATION = 'RECEIVE_NEW_BUSS_LOCATION';
export const SEND_NEW_BUSS_LOCATION = 'SEND_NEW_BUSS_LOCATION';

export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET_MESSAGE';
export const WEBSOCKET_SEND = 'WEBSOCKET_SEND';